
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BoDServer", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:8733/Ball_of_Duty_Server/Domain/BoDServer/?wsdl")
public class BoDServer
    extends Service
{

    private final static URL BODSERVER_WSDL_LOCATION;
    private final static WebServiceException BODSERVER_EXCEPTION;
    private final static QName BODSERVER_QNAME = new QName("http://tempuri.org/", "BoDServer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8733/Ball_of_Duty_Server/Domain/BoDServer/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BODSERVER_WSDL_LOCATION = url;
        BODSERVER_EXCEPTION = e;
    }

    public BoDServer() {
        super(__getWsdlLocation(), BODSERVER_QNAME);
    }

    public BoDServer(WebServiceFeature... features) {
        super(__getWsdlLocation(), BODSERVER_QNAME, features);
    }

    public BoDServer(URL wsdlLocation) {
        super(wsdlLocation, BODSERVER_QNAME);
    }

    public BoDServer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BODSERVER_QNAME, features);
    }

    public BoDServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BoDServer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBoDServer
     */
    @WebEndpoint(name = "BasicHttpBinding_IBoDServer")
    public IBoDServer getBasicHttpBindingIBoDServer() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IBoDServer"), IBoDServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBoDServer
     */
    @WebEndpoint(name = "BasicHttpBinding_IBoDServer")
    public IBoDServer getBasicHttpBindingIBoDServer(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IBoDServer"), IBoDServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BODSERVER_EXCEPTION!= null) {
            throw BODSERVER_EXCEPTION;
        }
        return BODSERVER_WSDL_LOCATION;
    }

}
