
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.ball_of_duty_server.ArrayOfServerGameObject;
import org.datacontract.schemas._2004._07.ball_of_duty_server.ServerPlayer;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBoDServer", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.ball_of_duty_server.ObjectFactory.class,
    org.datacontract.schemas._2004._07.system.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IBoDServer {


    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.ball_of_duty_server.ServerPlayer
     */
    @WebMethod(action = "http://tempuri.org/IBoDServer/newGuest")
    @WebResult(name = "newGuestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "newGuest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NewGuest")
    @ResponseWrapper(localName = "newGuestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NewGuestResponse")
    public ServerPlayer newGuest();

    /**
     * 
     * @param clientPlayer
     * @return
     *     returns org.datacontract.schemas._2004._07.ball_of_duty_server.ArrayOfServerGameObject
     */
    @WebMethod(action = "http://tempuri.org/IBoDServer/joinGame")
    @WebResult(name = "joinGameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "joinGame", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JoinGame")
    @ResponseWrapper(localName = "joinGameResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JoinGameResponse")
    public ArrayOfServerGameObject joinGame(
        @WebParam(name = "clientPlayer", targetNamespace = "http://tempuri.org/")
        ServerPlayer clientPlayer);

}
